USE [master]
GO

/****** Object:  Database [Mekan]    Script Date: 18.01.2016 19:03:15 ******/
CREATE DATABASE [Mekan]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mekan', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Mekan.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Mekan_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Mekan_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Mekan] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mekan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Mekan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Mekan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Mekan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Mekan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Mekan] SET ARITHABORT OFF 
GO

ALTER DATABASE [Mekan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Mekan] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Mekan] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Mekan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Mekan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Mekan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Mekan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Mekan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Mekan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Mekan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Mekan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Mekan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Mekan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Mekan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Mekan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Mekan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Mekan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Mekan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Mekan] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Mekan] SET  MULTI_USER 
GO

ALTER DATABASE [Mekan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Mekan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Mekan] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Mekan] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Mekan] SET  READ_WRITE 
GO


