//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mekan_Sitesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MekanEntities10 : DbContext
    {
        public MekanEntities10()
            : base("name=MekanEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Degerlendirme> Degerlendirme { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<Mekanlar> Mekanlar { get; set; }
        public DbSet<OnayBekleyen> OnayBekleyen { get; set; }
        public DbSet<Reddedilen> Reddedilen { get; set; }
    }
}
