//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mekan_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnayBekleyen
    {
        public int ID { get; set; }
        public string MekanSahibi { get; set; }
        public string MekanAd { get; set; }
        public string Resim { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string Gonderen { get; set; }
    }
}
